### ISSUE TITLE
Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "fr" in Intl.NumberFormat

### ISSUE THREAD

**Issue by oliverlj** [timbru31/docker-node-chrome#373]
I don't know if this related to this image. I have no issue on local.
We have this issue since one or two month now in our gitlab-ci

```
not ok 1 Chrome 107.0 - [1782 ms] - Unit | Service | wasm | definition | uphold: it should import deposit
    ---
        actual: >
            null
        stack: >
            Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "fr" in Intl.NumberFormat. Using default locale: "fr" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details
            
                at new MissingDataError (webpack://__ember_auto_import__/../node_modules/@formatjs/intl/lib/src/error.js?:15:890)
                at createIntl (webpack://__ember_auto_import__/../node_modules/@formatjs/intl/lib/src/create-intl.js?:24:138)
                at _class2.createIntl (http://localhost:7357/assets/vendor.js:76784:35)
                at _class2.getOrCreateIntl (http://localhost:7357/assets/vendor.js:76763:34)
                at _class2.addTranslations (http://localhost:7357/assets/vendor.js:76853:12)
                at http://localhost:7357/assets/vendor.js:76224:15
                at Array.forEach (<anonymous>)
                at hydrate (http://localhost:7357/assets/vendor.js:76222:27)
                at new _class2 (http://localhost:7357/assets/vendor.js:76708:28)
                at _class2.create (http://localhost:7357/assets/vendor.js:2[111](https://gitlab.com/c1560/cryptofiscafacile/-/jobs/3332394333#L111)3:20)
        message: >
            Promise rejected before "it should import deposit": [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "fr" in Intl.NumberFormat. Using default locale: "fr" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details
            
        negative: >
            false
        browser log: |
    ...
```

**Comment by oliverlj** [comment]
This began to pop from chromium 103 to 104
I don't see this issue on local dev with chromium 107

**Comment by oliverlj** [comment]
found it, alpine 3.16 do not add all icu
can you please add package  icu-data-full@edge ?

**Comment by timbru31** [comment]
Sorry for the late response. I can see that your CI with Node.js 18 is working (again). Please let me know once the issue happens again. Normally alpine 3.17 should be used everywhere.
